.Dd February 16, 2021
.Dt MINIDENTD 1
.Os
.Sh NAME
.Nm minidentd
.Nd small UCSPI[1] server application that answers IDENT requests
.Sh SYNOPSIS
.Nm
.Op Fl v
.Op Fl n | Fl i | Fl r
.Op Fl y Ar file
.Op Fl t Ar timeout
.Sh DESCRIPTION
.Nm
reads a series of IDENT requests on stdin and answers them on stdout.
It logs what it's doing on stderr.
The environment variables
.Ev \& Ns Ar x Ns LOCALIP
and
.Ev \& Ns Ar x Ns REMOTEIP ,
where
.Ar x
is the value of the PROTO environment variable, must contain the IDENT
server address and the IDENT client address, respectively.
.Pp
.Nm
exits 0 on success, 100 on a usage error and 111 on a system call
failure.
.Pp
.Nm
does not contact the network directly.
It's meant to run under a super-server like
.Xr s6-tcpserver 1 .
.Nm
will work with IPv4 as well as IPv6.
.Pp
.Nm
works only under Linux (2.2 or later); on other systems, it will
compile and run, but report an error for every request.
.Pp
The problem is that
.Em there is no portable Unix way
of listing active outgoing TCP connections with the relevant uids.
On Linux,
.Nm
parses the
.Pa /proc/net/tcp
or
.Pa /proc/net/tcp6
virtual file.
Other systems have their own way of doing this, if you want your
system to be supported by
.Nm ,
please contact the author.
.Sh OPTIONS
.Bl -tag -width x
.It Fl v
Verbose mode.
Log queries and replies.
.It Fl n
Send ERROR : HIDDEN-USER replies if the user has a
.Pa .ident
file in their home directory.
.It Fl i
User-defined answers.
The first 14 chars of the user's
.Pa .ident
file, up to EOF or newline, are used instead of the user name.
If the file exists and is empty, send ERROR : HIDDEN-USER.
If it doesn't exist, send a normal reply.
.It Fl r
Send random replies.
.It Fl y Ar file
Valid with
.Ql -n
or
.Ql -i .
Use
.Ar file
instead of
.Pa .ident .
.It Fl t Ar timeout
Close connection after
.Ar timeout
milliseconds without a client request.
.El
.Sh SEE ALSO
.Xr s6-ident-client 1 ,
.Xr s6-tcpserver 1
.Pp
[1]
.Lk https://cr.yp.to/proto/ucspi.txt
.Pp
This man page is ported from the authoritative documentation at:
.Lk https://skarnet.org/software/s6-networking/minidentd.html
.Sh AUTHORS
.An Laurent Bercot
.An Alexis Ao Mt flexibeast@gmail.com Ac (man page port)
